### ISSUE TITLE
Update Flask Version

### ISSUE THREAD

**Issue by diegoborbadev** [diegoborbadev/pytube-downloader#20]
Verify the possibility to use a newer Flask version in the application.

**Comment by LyubomirT** [comment]
I examined this issue and it seems like the project doesn't work with `Flask` 2.2.2, even though it's listed in the dependencies. After upgrading to the latest version (3.0.0) it seems like things are working again.

**Comment by diegoborbadev** [comment]
> I examined this issue and it seems like the project doesn't work with `Flask` 2.2.2...

How did you test it? It supposed to be working...

**Comment by LyubomirT** [comment]
> > I examined this issue and it seems like the project doesn't work with `Flask` 2.2.2...
> 
> How did you test it? It supposed to be working...

First I created a virtual environment in the project folder (basic `venv`), then activated it and installed the needed dependencies. After the installation process finished I tried to run the project and got a werkzeug error immediately, which caused the app to crash.

**Comment by diegoborbadev** [comment]
This is strange because it is working on the demo server and locally for me (but I'm not using a `venv`). 

But this improvement is important anyway.
