### ISSUE TITLE
New User Interface (UI)

### ISSUE THREAD

**Issue by diegoborbadev** [diegoborbadev/pytube-downloader#25]
_Originally posted by @codeIntrovert in https://github.com/diegoborbadev/pytube-downloader/issues/24#issuecomment-1890364767_

**Comment by codeIntrovert** [comment]
Sure, assign me the issue i'll make a new UI for pyTube

**Comment by codeIntrovert** [comment]
starting development 🙌

**Comment by codeIntrovert** [comment]
### Progress So Far
![image](https://github.com/diegoborbadev/pytube-downloader/assets/46672438/42f9e9f5-3adb-42bb-84a4-6be2f479e0e8)
![image](https://github.com/diegoborbadev/pytube-downloader/assets/46672438/e2160103-ae3d-406e-9ffa-21df7e2388ae)

**Comment by diegoborbadev** [comment]
Wow! Looks awesome! 🎉

Just don't forget about mobile responsiveness!

**Comment by codeIntrovert** [comment]
The design is ready, and it looks great! I have taken great care of responsiveness, ensuring it looks good on every device, including phones and desktops.

But, there is a slight bug while working on the UI in the streams.html file. Whenever I input a link in the input box(on home page), it redirects to /streams and shows a 'Bad request' error. 

Could you help me fix this bug, or should I make the pull request with the bug? I'm only good in frontend development :(
